### ISSUE TITLE
Error when trying to create a login

### ISSUE THREAD

**Issue by manueliglesiasgarcia** [corpusops/bitwardentools#1]
Trying to create a secret in a organization results in a error tested against a Bitwarden_RS instance
Here It's the code to reproduce the error
```
from bitwardentools import client as bwclient
from variables import email,password,server,organization

client = bwclient.Client(server, email, password)
client.sync()

orga = client.get_organization(organization)

cipherp = {
    "object": "item",
    "name": "testitp",
    "organizationId": orga.id,
    "notes": "supernote",
    "login": {"username": "alice", "password": "rabbit"},
}

cipher = client.create(**cipherp)
```
Here It's the traceback
```
Traceback (most recent call last):
  File "/home/manu/Documents/Cloudsphere/DevOps/tools/bitwarden-restapi/teste.py", line 9, in <module>
    cipher = client.create(**{
  File "/home/manu/.local/lib/python3.9/site-packages/bitwardentools/client.py", line 1551, in create
    return BWFactory.create(self, *args, **kw)
  File "/home/manu/.local/lib/python3.9/site-packages/bitwardentools/client.py", line 368, in create
    return kls.patch("create", client, *args, **kw)
  File "/home/manu/.local/lib/python3.9/site-packages/bitwardentools/client.py", line 363, in patch
    ret = api_method(**jsond)
  File "/home/manu/.local/lib/python3.9/site-packages/bitwardentools/client.py", line 976, in create_item
    obj = self._upload_object(u, method=method, data=data, key=key, log=log)
  File "/home/manu/.local/lib/python3.9/site-packages/bitwardentools/client.py", line 876, in _upload_object
    assert resp.status_code == 200
AssertionError
```

**Comment by kiorky** [comment]
I do not announced it because it's a bit in a wave for now, im just in the beginning of the writing of this API client.

Can you upgrade or pull latest (be aware that i rewrote history a bit as it is not still really released.)

That code is already tested, and i confirm it to work in our configurations (see [compose setup](https://github.com/corpusops/bitwardentools/blob/main/docker-compose-test.yml) for tests, for example).

To get more debug infos, can you put a pdb on client.py in the _upload_object method and inspect what's in the response body ?

**Comment by kiorky** [comment]
I have test failures with 1.20.0, i think something has changed with `1.18.0` that we were using in the stack.

I ll fix that ;).

**Comment by kiorky** [comment]
you can try latest release / HEAD.

**Comment by manueliglesiasgarcia** [comment]
Yeah seems that now It's working correctly the only thing that was missing was the "collectionIds" that It's still mising in the USAGE.md
```
from bitwardentools import client as bwclient
from variables import email,password,server,organization

client = bwclient.Client(server, email, password)
client.sync()
orga = client.get_organization(organization)
collection = client.get_collection("Default Collection",orga=orga)

cipherp = {
    "object": "item",
    "name": "testitp",
    "organizationId": orga.id,
    "notes": "supernote",
    "login": {"username": "alice", "password": "rabbit"},
    "collectionIds": [collection.id],
}

cipher = client.create(**cipherp)
```

**Comment by kiorky** [comment]
Yes and no, [...], i have to test it further, seems it's now since `1.19+` impossible to add secrets which arent tied to any collection.

I was able to do it before.

**Comment by manueliglesiasgarcia** [comment]
I'll be closing the issue due to there's no further problems with this
