### ISSUE TITLE
add TOTP support

### ISSUE THREAD

**Issue by perkons** [corpusops/bitwardentools#11]
We would like to use bitwardentools with TOTP as we require all users to have 2FA with Google Authenticator, Authy or other. Would be nice to have the option to use the Authenticator Key in the client. Something like this:
`client = Client('https://bitwarden.example.com', 'user@example.com', 'user_password', 'authenticator_key');`

**Comment by kiorky** [comment]
PR are welcome :o)

I wont have the time to do it myself right now .

**Comment by mfominov** [comment]
U won't need totp while using api_key/secret.
In that case #14 is more valuable feature.

**Comment by mfominov** [comment]
`
BITWARDEN_TOKEN=$(curl --location -s --request POST \
  ${BITWARDEN_URL}/identity/connect/token \
  --header "Content-Type: application/x-www-form-urlencoded" \
  --data-urlencode "grant_type=client_credentials" \
  --data-urlencode "scope=api" \
  --data-urlencode 'deviceName=chrome' \
  --data-urlencode 'deviceIdentifier=DEVICE_ID' \
  --data-urlencode 'deviceType=DEVICE_TYPE' \
  --data-urlencode "username=${BITWARDEN_USER}" \
  --data-urlencode "client_id=${BITWARDEN_CLIENID}" \
  --data-urlencode "client_secret=${BITWARDEN_SECRET}" | jq -r '.access_token')
`

**Comment by kiorky** [comment]
dup #14
