### ISSUE TITLE
add edit_item/edit_login functionality

### ISSUE THREAD

**Issue by perkons** [corpusops/bitwardentools#12]
Would be nice to have an option to edit/update existing items. Here https://pypi.org/project/bitwardentools/ it does not say if edit itmes/logins is possible, but I can see in the pyton code `edit_login = edit_item`. Is this supported already?

I am able to add items, logins, collections and get ciphers, but not edit or update.
I have tried to update the password of a login with JSON payload like this:
```
>>> payload = {
...     "login": {
...         "username": "root", "password": "password2"
...     }
... }
>>> client.edit_login("server1", orga="organization1", collections=["collection1"], **payload)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/bitwardentools/client.py", line 1297, in edit_item
    return self.create_item(*a, **kw)
  File "/home/user/.local/lib/python3.10/site-packages/bitwardentools/client.py", line 1265, in create_item
    u = f'/api/ciphers/{data["id"]}'
KeyError: 'id'
>>> client.edit_login(name="server1", orga="organization1", collection="collection1", **payload)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/bitwardentools/client.py", line 1297, in edit_item
    return self.create_item(*a, **kw)
  File "/home/user/.local/lib/python3.10/site-packages/bitwardentools/client.py", line 1265, in create_item
    u = f'/api/ciphers/{data["id"]}'
KeyError: 'id'
>>>
```

OS: Fedora 35
Python: 3.10

**Comment by kiorky** [comment]
see https://github.com/corpusops/bitwardentools/blob/main/src/tests/test_client.py#L263

**Comment by maciej-rek** [comment]
Hi, I'm trying to edit the username but I have no idea what I'm doing wrong. I looked at the linked code and successfully edited the note. Can you tell me what I'm doing wrong?

# WORKING GREAT
secitem = client.search_objects({"name": 'sv_admin'}, sync=True)[0]
client.edit_item(secitem, note="its test only")

# DON'T WORK
secitem = client.search_objects({"name": 'sv_admin'}, sync=True)[0]
client.edit_login(secitem, username="svroot")
client.edit_login(secitem, password="svroot")

Thank you, and sorry for reopen this :)
