### ISSUE TITLE
Dev requirements

### ISSUE THREAD

**Issue by mredaelli** [corpusops/bitwardentools#21]
Hello!

I was wondering, why do you have requirements marked as dev in `requirements.txt`?

https://github.com/corpusops/bitwardentools/blob/main/requirements/requirements.txt#L10

I'm asking because I'd rather not install ipython and jedi when I install `bitwardentools` in pipelines and such :)

**Comment by jankatins** [comment]
I was curious: they also get pulled into setup.py install_requires: https://github.com/corpusops/bitwardentools/blob/main/setup.py#L34

```py
install_requires = [
    a.strip()
    for a in open("requirements/requirements.txt").read().splitlines()
    if req.search(a) and a.strip()
]
```

**Comment by kiorky** [comment]
fixed in latest release.
