### ISSUE TITLE
Bitwardentools bw always asks for master password

### ISSUE THREAD

**Issue by rforberger** [corpusops/bitwardentools#23]
Hi,
I tried to use bitwardentools and found out, that when being logged in, bw always asks for the master password again.

Could someone explain me?

Best regards,

Ronny Forberger

**Comment by rforberger** [comment]
This seems to be a bug.

**Comment by kiorky** [comment]
You should give reproducible code for us to help you.

**Comment by rforberger** [comment]
Sorry don't need the solution anymore.
