### ISSUE TITLE
 passwords    Cant decrypt cipher 5bc9ae26-b873-4261-8d7e-a739088b39f4, broken ? (client.py:1710)

### ISSUE THREAD

**Issue by commonism** [corpusops/bitwardentools#32]
Recently I noticed I got some credentials in vaultwarden which were not accessible using bitwardentools.

bitwardentools been logging
```
 passwords    Cant decrypt cipher 5bc9ae26-b873-4261-8d7e-a739088b39f4, broken ? (client.py:1710)
```

I've tracked it down to:

https://github.com/corpusops/bitwardentools/blob/cd8748c6c51b09921ff57a53006090c48f0f5858/src/bitwardentools/crypto.py#L213-L217
The "Symetric hmac verification failed" is swallowed on the way.

The credentiala are part of a collection, other credentials of the same collection work fine.

New credentials created using the bitwarden browser plugin or vaultwardenweb are unreadable by bitwardentools, fine to use in browser plugin.

**Comment by commonism** [comment]
vaultwarden-web is not affected (yet?), but recent versions of the bitwarden browser plugin use the key field on the item to store a key to use instead of the org/user key.
bitwarden-tools do not honor the items key and use the org/user key instead, failing the hmac.

possible fix is:
https://github.com/corpusops/bitwardentools/pull/33/commits/da98abd073497050e58202f55c7e11a62441447b

**Comment by kiorky** [comment]
fixed in latest release.
