### ISSUE TITLE
Error with get_cipher

### ISSUE THREAD

**Issue by mfominov** [corpusops/bitwardentools#9]
First of all, thx a lot for this library.

I'm trying to use it on self hosted vaultwarden instance and faced an issue.
code
`cipher = client.get_cipher(item_or_id_or_name="elk", collection=col, orga=orga)`
error
`Traceback (most recent call last):
  File "main.py", line 21, in <module>
    cipher = client.get_cipher(item_or_id_or_name="elk", collection=col, orga=orga)
  File "/home/vscode/.local/lib/python3.8/site-packages/bitwardentools/client.py", line 1883, in get_cipher
    ret = ret[0]
TypeError: 'odict_values' object is not subscriptable`

Can u help me?

**Comment by mfominov** [comment]
By with as_list=True i have an output.
`
odict_values([<bitwardentools.client.Login object at 0xffffb49c7d90>])
`
But how to get a values inside of object?

**Comment by kaotika** [comment]
Thanks @mfominov . `as_list=True` helped. But I needed to mangle around with the result to get the real cipher.

```python
cipher_list = client.get_cipher(item_or_id_or_name="elk", as_list=True)
cipher = list(cipher_list)[0]
print(cipher.id)
```

**Comment by mfominov** [comment]
@kaotika thx)

`
cipher_list = client.get_cipher(
    "elk", collection=col, orga=orga, as_list=True, sync=True
)
cipher = list(cipher_list)[0]

print(cipher.data["username"])
print(cipher.data["password"])
`
